name: code_review

on:
    pull_request:
        branches:
            - master
        types:
            - opened

jobs:
    review:
        runs-on: self-hosted

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get pull request details
              id: get_pr
              uses: octokit/request-action@v2.x
              with:
                route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
                mediaType: 'application/vnd.github.v3+json'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

            - name: Check for review trigger in PR message
              id: check_review_trigger
              run: |
                echo "PR_BODY=$(echo '${{ steps.get_pr.outputs.data }}' | jq -r '.body')" >> $GITHUB_ENV
                if [[ "${PR_BODY}" != *"#ollama_review"* ]]; then
                  echo "Review trigger not found in PR message. Exiting."
                  exit 0
                fi

            - name: Run review script
              shell: bash
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB.TOKEN }}
              run: |
                echo .github/scripts/pull_request_review.py
                echo --github_sha ${{ github.sha }}
                echo --github_sha ${{ github.sha }}
                echo --repository ${{ github.repository }}
                echo --pull_request_number ${{ github.event.number }}

                python3 -m pip install --upgrade --user pip
                pip install --user requests

                python3 .github/scripts/pull_request_review.py
              if: env.PR_BODY != ''

