name: code_review

on:
    pull_request:
        branches:
            - master
        types:
            - opened

jobs:
    review:
        runs-on: [self-hosted, 7e08740fb4b5]
        timeout-minutes: 10  # 10분 후 타임아웃

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Check if runner is active
              run: |
                if [ -z "${RUNNER_NAME}" ]; then
                  echo "Runner is not active."
                  exit 1
                else
                  echo "Runner is active: ${RUNNER_NAME}"
                fi
        
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get pull request details
              id: get_pr
              uses: octokit/request-action@v2.x
              with:
                route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
                mediaType: 'application/vnd.github.v3+json'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Check for review trigger in PR message
              id: check_review_trigger
              run: |
                if echo "${{ github.event.pull_request.body }}" | grep -q "#review"; then
                  echo "contains_review_tag=true" >> $GITHUB_ENV
                else
                  echo "contains_review_tag=false" >> $GITHUB_ENV
                  echo "cannot find"
                fi

            - name: Run review script
              shell: bash
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
              if: env.contains_review_tag == 'true'
              run: |
                echo .github/scripts/pull_request_review.py
                echo --github_sha ${{ github.sha }}
                echo --repository ${{ github.repository }}
                echo --pull_request_number ${{ github.event.number }}

                python3 -m pip install --upgrade --user pip
                pip install --user requests

                python3 .github/scripts/pull_request_review.py
